services: docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.gitlab.com
  - docker pull registry.gitlab.com/documentation-as-code/documentation-as-code/asciidoctor:1.5.8
  - docker run registry.gitlab.com/documentation-as-code/documentation-as-code/asciidoctor:1.5.8 /bin/bash -c "yarn install"

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master